# Server settings (ServerProperties)
server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  application:
    name: user
  profiles:
    active: ci