# Server settings (ServerProperties)
server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress:  false
    ipAddress: 127.0.0.1
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  cloud:
    client:
      ipAddress: 127.0.0.1
  application:
    name: user
  profiles:
    active: ci